BUN_NAME = 'булка'
BUN_PRICE = 100
SAUCE_INGREDIENT_TYPE = 'соус'
SAUCE_INGREDIENT_NAME = 'сырный'
SAUCE_INGREDIENT_PRICE = 50
CUTLET_INGREDIENT_TYPE = 'начинка'
CUTLET_INGREDIENT_NAME = 'котлета'
CUTLET_INGREDIENT_PRICE = 100